### ISSUE TITLE
missing releasekey.x509.pem

### ISSUE THREAD

**Issue by ghost** [mikeperry-tor/mission-improbable#49]
java.io.FileNotFoundException: ./releasekey.x509.pem (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.android.dumpkey.DumpPublicKey.main(DumpPublicKey.java:239)

**Comment by ghost** [comment]
@mikeperry-tor and help with this?

**Comment by tyler-morrison** [comment]
@mikeperry-tor I noticed this issue as well.
